const skins = [
{
champion: "Butterfly",
name: "Castorice",
IOS: "https://link4m.com/pCSAmWd",
Android: "https://link4m.com/ibMoLj",
bgImg: "img/castorice.png",
miniImg: "img/castorice_mini.png",
label: "Mới",
desc: "Effects - Sound - Button",
color: "200, 111, 255",
},
{
champion: "Allain",
name: "Firefly",
IOS: "https://link4m.com/3Rfs8iBP",
Android: "https://link4m.com/KoWHWeu8",
bgImg: "img/firefly.png",
miniImg: "img/firefly_mini.png",
label: "Mới",
desc: "Effects - Sound - Button",
color: "0, 225, 160",
},
{
champion: "Allain",
name: "Hắc Kiếm Sĩ Kirito",
IOS: "https://link4m.com/lbGyd",
Android: "https://link4m.com/lbGyd",
bgImg: "img/53701.jpg",
miniImg: "img/305371head.jpg",
label: "Mới",
desc: "Effects - Sound",
color: "150, 150, 150",
},
{
champion: "Allain",
name: "Kirito",
IOS: "https://link4m.com/DblwR",
Android: "https://link4m.com/DblwR",
bgImg: "img/53702.jpg",
miniImg: "img/305372head.jpg",
label: "Mới",
desc: "Effects - Sound",
color: "100, 225, 255",
},
{
champion: "Allain",
name: "Tuyết Sơn Song Kiếm",
IOS: "https://link4m.com/ZGQkj",
Android: "https://link4m.com/ZGQkj",
bgImg: "img/53703.jpg",
miniImg: "img/305373head.jpg",
label: "Mới",
desc: "Effects - Sound",
color: "160, 225, 255",
},
{
champion: "Thorne",
name: "Thứ Nguyên Vệ Thần",
IOS: "https://link4m.com/B6FC0",
Android: "https://link4m.com/woMGnt8",
bgImg: "img/13314.jpg",
miniImg: "img/13314head.jpg",
label: "Mới",
desc: "Effects - Sound - Button",
color: "0, 150, 255",
},
];