const skins = [
{
champion: "Butterfly",
name: "Castorice",
IOS: "https://link4m.com/HNuFcrPB",
Android: "https://link4m.com/bGw6Js",
bgImg: "img/castorice.png",
miniImg: "img/castorice_mini.png",
label: "Mới",
desc: "Effects - Sound - Button",
color: "150, 123, 255",
},
{
champion: "Allain",
name: "Firefly",
IOS: "https://link4m.com/zo0y0",
Android: "https://link4m.com/mgC7yVib",
bgImg: "img/firefly.png",
miniImg: "img/firefly_mini.png",
label: "Mới",
desc: "Effects - Sound - Button",
color: "0, 255, 180",
},
{
champion: "Thorne",
name: "Thứ Nguyên Vệ Thần",
IOS: "https://link4m.com/hCS9pdPc",
Android: "https://link4m.com/j8RC873",
bgImg: "img/13314.jpg",
miniImg: "img/13314head.jpg",
label: "Mới",
desc: "Effects - Sound - Button",
color: "50, 150, 255",
},
{
champion: "Nakroth",
name: "Xiao",
IOS: "https://link4m.com/ihY9gGLg",
Android: "https://link4m.com/QcuSACv",
bgImg: "img/xiao.png",
miniImg: "img/xiao_mini.png",
label: "Mới",
desc: "Effects - Sound - Button",
color: "0, 255, 200",
}
];